# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='icon',
            field=models.CharField(blank=True, max_length=128, verbose_name='Иконка страны'),
        ),
    ]
